### ISSUE TITLE
how do I get the css file?

### ISSUE THREAD

**Issue by geralddzx** [VonD/text-angular-rails#1]

**Comment by VonD** [comment]
Hi,

this is an old version of the package, I haven't updated it in a year. Styling was done in js then.
If you want to upgrade the assets to a new version of text-angular, I'll accept the PR and publish the new  version of the gem. (just replace the assets files in the vendor directory).
Otherwise you may consider using bower for this kind of dependencies.

Cheers

**Comment by geralddzx** [comment]
I see, I'm manually loading the js and css then. Thanks!
